# Generated by Django 6.1 on 2026-09-09 07:29

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=20)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 9, 7, 29, 43, 42448)),
        ),
    ]
