# Generated by Django 6.1 on 2026-09-09 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projects_alter_experience_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 9, 7, 46, 26, 194449)),
        ),
    ]
