# Generated by Django 6.1 on 2026-09-22 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_experience_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 22, 5, 48, 43, 585181, tzinfo=datetime.timezone.utc)),
        ),
    ]
